# Site settings
title: "EstudiantesRSEF - Grupo Especializado de Estudiantes de la Real Sociedad Española de Física."
description: "EstudiantesRSEF es el Grupo Especializado de Estudiantes de la Real Sociedad Española de Física, cuyo objetivo es reunir a estudiantes de ciencias físicas de universidades españolas y conseguir una mayor participación del colectivo en las instituciones, tanto en el ámbito nacional como internacional, a través de actividades que complementen los currículos oficiales que fomenten la divulgación científica en la sociedad y promuevan la colaboración con agrupaciones del mismo ámbito de todo el mundo."
banner: img/banner.png
# url: "http://yourdomain.com" # the base hostname & protocol for your site
destination: ../site/
locale: "es"

# Build settings
markdown: kramdown
future: true
permalink: /blog/:year/:month/:day/:title/

#facebook
fb_admins:
fb_appid:

#Collections
collections:
  events:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

gems:
 - jekyll-redirect-from
 - jekyll-sitemap
